# Generated by Django 3.2.3 on 2021-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20210930_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
