# Generated by Django 3.2.3 on 2021-10-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text_content',
            field=models.TextField(max_length=500),
        ),
    ]
