# Generated by Django 3.2.3 on 2021-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0007_alter_posts_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
